# Generated by Django 4.1.4 on 2022-12-23 12:46

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_profile_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None, verbose_name='Цвет фона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='border_color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None, verbose_name='Цвет рамки'),
        ),
    ]
