# Generated by Django 4.1.4 on 2022-12-23 13:47

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_initial'),
        ('userprofile', '0004_alter_profile_background_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackColors',
        ),
        migrations.DeleteModel(
            name='BorderColors',
        ),
        migrations.AddField(
            model_name='profile',
            name='tests',
            field=models.ManyToManyField(blank=True, to='questionnaire.test'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='background_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Цвет фона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='border_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Цвет рамки'),
        ),
    ]
